### ISSUE TITLE
Epic: Q3 2023 Wishlist & Roadmap

### ISSUE THREAD

**Issue by haochenx** [kxcdev/ocaml-general-gha#4]
# Q3 2023 Wishlist & Roadmap

## Unplanned
- [ ] GitHub Pages support
  - odoc support
    - [x] basic odoc support
    - [ ] streamline usage of `@doc-private`
    - [ ] allow specifying alternative odoc site path
- [ ] coverage (i.e. bisect_ppx) support
- [ ] perf benchmark support
- [ ] `dune fmt` support
  - [ ] initial support (check only)
  - [ ] separate ci check report item
  - [ ] auto promote?
    - create branch + pr?
    - directly push?
- [ ] generated resource check
  - [ ] initial support
  - [ ] separate ci check report item
  - [ ] multi config, config items:
    - [ ] dune profile
    - [ ] build target (dir) & alias(es)
    - [ ] --build_dir
    - [ ] diff directory
  - [ ] auto promote?
    - create branch + pr?
    - directly push?
- GitHub GUI Reporting
  - [ ] better docker image variation display
  - [ ] collapse long test result
  - [ ] colorize test result
  - [ ] consolidate test result report for variants
  - [ ] opam "relock" diff
- Local Execution Support
  - [ ] decouple configuration from GitHub Actions
  - [ ] provide utilities for local execution (i.e. (almost eqv.) spin adequate docker containers)
- Customization of ocaml-general images
  - best situation workflow:
    - prerequisites:
      - (ocaml-general) multiple "flavor" (i.e. native + opam package collection & matrix config) support
    - fork https://github.com/kxcinc/pubinfra.dockerfiles/tree/main/ocaml-general
    - add non-kxc flavor
    - github actions deploy automatically
    - specify ghcr base image and "flavor" to use in ocaml-general-gha
- Internal Technical Improvements
  - [ ] stop copying `docker-build-context/` to each one of generated/dockerfiles/*
